<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DonePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonePostRepository extends EntityRepository
{
    function findDonePostsOrderByDate($offset) {
        return $this->createQueryBuilder('ip')
            ->select(array('p.id', 'p.content', 'ip.doneAt as date', 'p.voteCount'))
            ->leftJoin('ip.post', 'p')
            ->orderBy('ip.doneAt', 'DESC')
            ->setFirstResult($offset)
            ->setMaxResults(10)
            ->getQuery()
            ->getScalarResult();
    }
}
